routes/web.php
<?php

use App\Coupon;
use App\Doctor;
use App\Http\Controllers\DoctorsController;
use App\Http\Controllers\HomeController;
use App\Product;
use App\User;
use Illuminate\Http\Request;


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*Header Routes*/

Route::get('/', function () {
    $section = 'consult';
    return view('home.index',compact([
        'section'
    ]));
})->name('index');



//User Routes
Route::post('user/address','AddressController@store')->name('users.address');
Route::get('/doctors', function () {
    $doctors = Doctor::all();
    $section = 'doctors';
    return view('user.findDoctor.doctors',compact([
        'doctors',
        'section'
    ]));
})->name('doctors.findDoctors');

Route::get('/pharma', function () {
    $products = Product::where('status','accept')->get()->take(5);

    $section = 'pharma';
    return view('user.pharma.index',compact([
        'section','products'
    ]));
})->name('pharma.index');


/*End of Header Routes*/


Route::get('/user/consult','User\UsersController@createChatAppointment')->name('users.chatAppointment');
Route::post('/user/consult/bookAppointment','User\UsersController@bookChatAppointment')->name('users.bookChatAppointment');

Route::post('/user/consult/checkChatAppointment','User\UsersController@checkChatBookedAppointment')->name('users.checkChatBookedAppointment');


Route::get('/pharma/single-product', function () {
    return view('user.pharma.single_product');
});

Route::get('/order/cart','CartController@index');
// Route::get('/order/checkout', function () {
//     return view('pharma.dashboard.cart.checkout');
// });
Route::get('/order/checkout','CartController@checkout')->name('cart.checkout');

// Route::get('/order/checkout', function () {
//     return view('pharma.dashboard.cart.checkout');
// });

Route::resource('doctor', 'User\DoctorsController');
Route::post('user\getCurrentLocation','User\UsersController@getCurrentLocation')->name('ajax.getCurrentLocation');
Route::post('doctor\getDoctors','User\DoctorsController@getDoctors')->name('ajax.getDoctors');

/*Login controller routes*/

Auth::routes();

Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::post('/getotp', 'Auth\RegisterController@generateMessage')->name('register.sendotp');
Route::post('/getotpforuser', 'Auth\RegisterController@generateMessageForUser')->name('sendotpForuser');
Route::get('/resendotp', 'Auth\RegisterController@resendOTP')->name('resend');
Route::post('/verifyotp', 'Auth\RegisterController@verifyOtp')->name('verifyotp');
Route::get('/home', 'HomeController@index')->name('home');

/*Login controller routes*/

Route::get('/doctors/{doctor}/appointment/{slot}/{type}','User\DoctorsController@confirmAppointment')->name('doctors.confirmAppointment');
Route::post('/doctors/{doctor}/appointment/{slot}/store/p','User\DoctorsController@bookPersonalAppointment')->name('doctors.bookPersonalAppointment');
Route::post('/doctors/{doctor}/appointment/{slot}/store/o','User\DoctorsController@bookOthersAppointment')->name('doctors.bookOthersAppointment');

Route::post('/doctor/getslot','User\DoctorsController@fetchNextDaySlots')->name('ajax.fetchNextDaySlots');
Route::get('/doctors/{doctor}','User\DoctorsController@show')->name('doctors.show');

Route::get('/chats/chat',function(){
    return view('chats.chat');
});

Route::get('/dashboard/doctor',function(){
    $section = "profile";
    return view('doctor.dashboard.index',compact([
        'section'
    ]));
})->name('doctor.dashboard');

/*Slots*/
Route::get('dashboard/doctor/slots/{SlotDate}/edit','Doctor\SlotsController@edit')->name('slot.edit');
Route::resource('dashboard/doctor/slots','Doctor\SlotsController')->except('edit','update','destroy');
Route::put('dashboard/doctor/slots/{SlotDate}/update','Doctor\SlotsController@update')->name('slot.update');
Route::post('dashboard/doctor/slots/delete','Doctor\SlotsController@destroy')->name('ajax.deleteSlot');
/*Slots End*/

/*Appointments*/
Route::resource('dashboard/doctor/appointments','Doctor\AppointmentsController');
Route::get('/dashboard/doctor/appointment/{appointment}/accept','Doctor\AppointmentsController@accept')->name('appointment.accept');
Route::get('/dashboard/doctor/appointment/{appointment}/reject','Doctor\AppointmentsController@reject')->name('appointment.reject');
Route::post('/get-chats-appointments','Doctor\AppointmentsController@getChatsAppointments')->name('get-chats-appointments');
Route::post('/get-previous-appointments','Doctor\AppointmentsController@getPreviousAppointments')->name('get-previous-appointments');
Route::post('/get-new-appointments','Doctor\AppointmentsController@getNewAppointments')->name('get-new-appointments');

Route::post('/dashboard/doctor/appointment/{appointment}/generatePdf','DynamicPDFController@generatePdf');

/*Appointments End*/

/* Dashboard Doctors */
Route::get('/dashboard/doctor/basic-details', 'Doctor\DoctorsController@index')->name('doctor.basic-details');
Route::get('/registerUser','Auth\RegisterController@registerUser')->name('home.registerUser');
Route::get('/registerDoctor','Auth\RegisterController@registerDoctor')->name('home.registerDoctor');
Route::post('/dashboard/doctor/medical-details', 'Doctor\DoctorsController@setBasicDetails')->name('doctor.medical-details');
Route::post('/dashboard/doctor/education', 'Doctor\DoctorsController@setEducation')->name('doctor.education');
Route::post('/dashboard/doctor/establishment', 'Doctor\DoctorsController@setEstablishment')->name('doctor.establishment');
Route::post('/dashboard/doctor/completed-profile', 'Doctor\DoctorsController@createDoctor')->name('doctor.completed');
Route::get('/dashboard/doctors',function(){
    return view('doctor.dashboard.basic-details');
});

/* Dashboard Doctors */

Route::get('/dashboard/user','User\UsersController@index')->name('user.dashboard.profile');
Route::get('/dashboard/user/{user}/edit','User\UsersController@editUser')->name('user.edit');
Route::put('/dashboard/user/update','User\UsersController@updateUserData')->name('user.updateData');

Route::post('doctor\getDoctors','User\DoctorsController@getDoctors')->name('ajax.getDoctors');

/* Dashboard users */


/*Chat routes*/
Route::get('/chats/chat',function(){
    return view('chats.chat');
});

Route::get('/receive',function(){

    $users = [];
    $arr = [];
    $appointments = auth()->user()->doctor->appointments;
    foreach($appointments as $appointment){
        $user = $appointment->user()->where($arr)->first();
        if($user)
            $users[] = $user;
        $arr[] = ['id','!=',$appointment->user->id];
    }
    return view('chat.receive',compact([
        'users'
    ]));
})->name('receive');
Route::get('/send',function(){
    $users = [];
    $arr = [];
    $appointments = auth()->user()->appointments;
    foreach($appointments as $appointment){
        $user = $appointment->doctor->user()->where($arr)->first();
        if($user)
            $users[] = $user;
        $arr[] = ['id','!=',$appointment->doctor->user->id];
    }
    return view('chat.send',compact([
        'users'
    ]));
})->name('send');

Route::post('/setchat','ChatsController@setChat')->name('chat.set');
Route::post('/send-chat','ChatsController@send')->name('chat.send');
Route::post('/receive-chat','ChatsController@received')->name('chat.received');
Route::post('/chat-update','ChatsController@chatUpdate')->name('chat.update');

Route::resource('document','User\MedicalRecordsController');

Route::post('document/updateData','User\MedicalRecordsController@updateData')->name('document.updateData');
Route::delete('document/destroyDocument/{medicalrecord}', 'User\MedicalRecordsController@destroyDocument')->name('document.destroyDocument');

/*Chat Routes*/



Route::get('/prescription', 'DynamicPDFController@index');
// Route::get('/dynamic_pdf', 'DynamicPDFController@index');
Route::get('/dynamic_pdf/pdf/', 'DynamicPDFController@pdf');
Route::post('/temp-pre', 'DynamicPDFController@index');

// Route::get('/prescription-form', 'DynamicPDFController@pf');
Route::get('/prescription-form',function(){
    return view('doctor.appointments.prescription-form',compact([

    ]));
});
Route::get('dashboard/user/slots','User\SlotsController@index')->name('user.appointments.index');
Route::get('dashboard/user/prescription','User\DoctorsController@showPrescriptions')->name('user.prescription');
Route::get('dashboard/user/orders','User\PharmaciesController@showOrders')->name('user.orders');

Route::post('/get-user','User\UsersController@getUser')->name('get-user');

/*pharma dashbaord*/
Route::delete('/dashboard/pharma/categories/destroy/{category}', 'Pharma\CategoriesController@destroy');
Route::delete('/dashboard/pharma/subcategories/destroy/{subcategory}', 'Pharma\SubcategoriesController@destroy');
Route::get('/dashboard/pharma/products/accept/{product}','Pharma\ProductsController@accept')->name('products.accept');
Route::get('/dashboard/pharma/products/reject/{product}','Pharma\ProductsController@reject')->name('products.reject');
Route::get('/dashboard/pharma/products/remove/{product}','Pharma\ProductsController@remove')->name('products.remove');
Route::get('/dashboard/pharma/category/{category}','Pharma\ProductsController@manageCategory')->name('products.manageCategory');
Route::get('/dashboard/pharma/subcategory/{subcategory}','Pharma\ProductsController@manageSubcategory')->name('products.manageSubcategory');

Route::resource('dashboard/pharma/products','Pharma\ProductsController');
Route::resource('dashboard/pharma/coupons','Pharma\CouponsController');
Route::resource('dashboard/pharma/categories','Pharma\CategoriesController');
Route::resource('dashboard/pharma/subcategories','Pharma\SubcategoriesController');
Route::get('/dashboard/pharma',function(){
    return view('pharma.dashboard.index');
})->name('pharma.dashboard');



Route::get('dashboard/pharma/manufacturerRequest','Pharma\ManufacturersController@index')->name('manufacturer.requests');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name'];

    public function subcategories()
    {
        return $this->hasMany(Subcategory::class);
    }
    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/Pharma/CategoriesController.php
<?php

namespace App\Http\Controllers\Pharma;


use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use App\Category;
use App\Http\Requests\Pharma\CreateCategoryRequest;
use App\Http\Requests\Pharma\UpdateCategoryRequest;

class CategoriesController extends Controller
{
    public function index()
    {
        $categories = Category::latest()->get();
        $i = 1;
        return view('pharma.dashboard.categories.manage',compact([
            'categories',
            'i'
        ]));
    }

    public function create()
    {
        return view('pharma.dashboard.categories.create');
    }

    public function store(CreateCategoryRequest $request)
    {
        $category = Category::create([
            'name'=>$request->name
        ]);
        session()->flash('success','Category Added Successfully!');
        return redirect(route('categories.index'));
    }


    public function show(Category $category)
    {
        //
    }

    public function edit(Category $category)
    {
        return view('pharma.dashboard.categories.edit',compact([
            'category'
        ]));
    }

    public function update(UpdateCategoryRequest $request, Category $category)
    {
        $data = $request->only(['name']);
        $category->update($data);
        // dd($category);
        session()->flash('success','Category Updated Successfully!');
        return redirect(route('categories.index'));
    }


    public function destroy(Category $category)
    {
        $category = Category::where("id",$category->id);
        $category->forceDelete();
        session()->flash('success','Category Deleted Successfully');
        return redirect()->back();
    }

    public function viewCategoryProducts($category){
        // dd($category);
        $categories = Category::all();
        $singleCategory = Category::where('id',$category)->first();
        $subCategories = $singleCategory->subcategories()->get();
        $products = $singleCategory->products()->where('status','accept')->get();
        $isInCart = false;
        $quantity = 1;

        return view('pharma.category',compact([
            'products','subCategories','categories','singleCategory','isInCart','quantity'
        ]));
    }


}

resources/views/pharma/dashboard/categories/create.blade.php
@extends('pharma.dashboard.layout')
@section('title','Practo | Pharma Dashboard')
@section('dashboard-title','Add Category')
@section('main-content')
    <form action="{{route('categories.store')}}" method="POST">
        @csrf
        <div class="col-md-12">
            <div class="card" style="box-shadow:none;margin-top:3rem">
                <div class="card-body">
                    <div class="col-md-6" >
                        <div class="form-group col-md-12">
                            <label for="name">Category Name</label>
                            <input type="text" required
                            value="{{old('name')}}"
                            class="form-control @error('name') is-invalid @enderror"
                            name="name" id="name">
                        </div>
                        @error('name')
                            <p class="text-danger">{{$message}}</p>
                        @enderror

                        
                        <div class="form-group col-md-6">
                            
                        </div>
                        <div class="form-group col-md-6">
                            <input type="submit"
                                class="btn btn-warning pull-right" value="Add Category">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/pharma/dashboard/categories/edit.blade.php
@extends('pharma.dashboard.layout')
@section('title','Practo | Pharma Dashboard')
@section('dashboard-title','Edit Category')
@section('main-content')
    <form action="{{route('categories.update',$category->id)}}" method="POST">
        @csrf
        @method('PUT')
        <div class="col-md-12">
            <div class="card" style="box-shadow:none;margin-top:3rem">
                <div class="card-body">
                    <div class="col-md-6" >
                        <div class="form-group col-md-12">
                            <label for="name">Category Name</label>
                            <input type="text" required
                            value="{{$category->name,old('name')}}"
                            class="form-control @error('name') is-invalid @enderror"
                            name="name" id="name">
                            @error('name')
                            <p class="text-danger">{{$message}}</p>
                            @enderror
                        </div>

                        
                        <div class="form-group col-md-6">
                            
                        </div>
                        <div class="form-group col-md-6">
                            <input type="submit"
                                class="btn btn-warning pull-right" value="Update Category">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/pharma/dashboard/categories/manage.blade.php
@extends('pharma.dashboard.layout')
@section('title','Practo | Pharma Dashboard')
@section('dashboard-title','Manage Categories')
@section('main-content')



    <div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" style="display:inline-block" id="exampleModalLabel">Delete Category</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true" style="color:white">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                    <label for="">Are you sure you want to delete this category?</label>
                    </div>
                    <div class="modal-footer">
                        <form action="" method="POST" id="delete-category" >
                        @csrf
                        @method('DELETE')
                            <input type="submit" class="btn btn-primary" id="delete" value="Delete">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </form>
                    </div>
                </div>
            </div>
        </div>


 <div style="float:right;margin-bottom:4%;" >
 <form action="{{route('subcategories.create')}}" >
    <input type="submit" class="btn btn-primary" value="+ Add Subcategory">
 </form>
 </div> 


<div class="card">

    <div class="card-body">
        <table class="table table-bordered" id="manage-category-table">
            <thead>
                <th>#</th>   
                <th>Name</th> 
                <th>Sub Categories</th> 
                <th>Actions</th>
            </thead>
            <tbody>
                @foreach($categories as $category)
                    <tr>
                        <td>
                            {{$i++}}
                        </td>
                        <td>
                            {{$category->name}}
                        </td>
                        <td>
                            @if(count($category->subcategories) > 0)
                                @foreach($category->subcategories as $subcategory)
                                <a href="{{route('products.manageSubcategory',$subcategory)}}" style="text-decoration:none;">{{ucfirst($subcategory->name)}}{{$loop->last ? '' : ','}}</a>
                                @endforeach
                            @else
                            -
                            @endif
                        </td>
                        <td>
                            <a href="{{route('categories.edit',$category->id)}}" class="btn btn-sm btn-primary">Edit</a>
                            @if(count($category->products) == 0)
                                <a href="#"  class="btn btn-danger btn-sm delete-trigger modal-trigger" data-toggle="modal" onclick="displayDeleteModalForm({{$category}})" data-target="#delete-modal">Delete</a>
                            @else 
                            <a href="{{route('products.manageCategory',$category)}}" class="btn btn-warning btn-sm">View All Products</a>
                            @endif
                            
                        </td>
                    </tr>
                @endforeach
                    
            </tbody>
        </table>
    </div>
</div>

@endsection
@section('page-level-scripts')
     <script>
         function displayDeleteModalForm($category) {
            var url = 'categories/destroy/'+$category.id;
            $("#delete-category").attr('action',url);
        }
         $(document).ready(function() {
        $('#manage-category-table').DataTable({
    
            "columnDefs": [
                        {
                            'orderable': false,
                            'targets': [-1]
                        }
                    ]
                });
        } );
     </script>
    
@endsection 
@section('page-level-styles')
    <style>
        .d-flex{
            display: flex;
        }
        .modal-backdrop{
            display: none;
        }
    </style>
@endsection