routes/web.php
<?php

use App\Coupon;
use App\Doctor;
use App\Http\Controllers\DoctorsController;
use App\Http\Controllers\HomeController;
use App\Product;
use App\User;
use Illuminate\Http\Request;


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*Header Routes*/

Route::get('/', function () {
    $section = 'consult';
    return view('home.index',compact([
        'section'
    ]));
})->name('index');



//User Routes
Route::post('user/address','AddressController@store')->name('users.address');
Route::get('/doctors', function () {
    $doctors = Doctor::all();
    $section = 'doctors';
    return view('user.findDoctor.doctors',compact([
        'doctors',
        'section'
    ]));
})->name('doctors.findDoctors');

Route::get('/pharma', function () {
    $products = Product::where('status','accept')->get()->take(5);

    $section = 'pharma';
    return view('user.pharma.index',compact([
        'section','products'
    ]));
})->name('pharma.index');


/*End of Header Routes*/


Route::get('/user/consult','User\UsersController@createChatAppointment')->name('users.chatAppointment');
Route::post('/user/consult/bookAppointment','User\UsersController@bookChatAppointment')->name('users.bookChatAppointment');

Route::post('/user/consult/checkChatAppointment','User\UsersController@checkChatBookedAppointment')->name('users.checkChatBookedAppointment');


Route::get('/pharma/single-product', function () {
    return view('user.pharma.single_product');
});

Route::get('/order/cart','CartController@index');
// Route::get('/order/checkout', function () {
//     return view('pharma.dashboard.cart.checkout');
// });
Route::get('/order/checkout','CartController@checkout')->name('cart.checkout');

// Route::get('/order/checkout', function () {
//     return view('pharma.dashboard.cart.checkout');
// });

Route::resource('doctor', 'User\DoctorsController');
Route::post('user\getCurrentLocation','User\UsersController@getCurrentLocation')->name('ajax.getCurrentLocation');
Route::post('doctor\getDoctors','User\DoctorsController@getDoctors')->name('ajax.getDoctors');

/*Login controller routes*/

Auth::routes();

Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::post('/getotp', 'Auth\RegisterController@generateMessage')->name('register.sendotp');
Route::post('/getotpforuser', 'Auth\RegisterController@generateMessageForUser')->name('sendotpForuser');
Route::get('/resendotp', 'Auth\RegisterController@resendOTP')->name('resend');
Route::post('/verifyotp', 'Auth\RegisterController@verifyOtp')->name('verifyotp');
Route::get('/home', 'HomeController@index')->name('home');

/*Login controller routes*/

Route::get('/doctors/{doctor}/appointment/{slot}/{type}','User\DoctorsController@confirmAppointment')->name('doctors.confirmAppointment');
Route::post('/doctors/{doctor}/appointment/{slot}/store/p','User\DoctorsController@bookPersonalAppointment')->name('doctors.bookPersonalAppointment');
Route::post('/doctors/{doctor}/appointment/{slot}/store/o','User\DoctorsController@bookOthersAppointment')->name('doctors.bookOthersAppointment');

Route::post('/doctor/getslot','User\DoctorsController@fetchNextDaySlots')->name('ajax.fetchNextDaySlots');
Route::get('/doctors/{doctor}','User\DoctorsController@show')->name('doctors.show');

Route::get('/chats/chat',function(){
    return view('chats.chat');
});

Route::get('/dashboard/doctor',function(){
    $section = "profile";
    return view('doctor.dashboard.index',compact([
        'section'
    ]));
})->name('doctor.dashboard');

/*Slots*/
Route::get('dashboard/doctor/slots/{SlotDate}/edit','Doctor\SlotsController@edit')->name('slot.edit');
Route::resource('dashboard/doctor/slots','Doctor\SlotsController')->except('edit','update','destroy');
Route::put('dashboard/doctor/slots/{SlotDate}/update','Doctor\SlotsController@update')->name('slot.update');
Route::post('dashboard/doctor/slots/delete','Doctor\SlotsController@destroy')->name('ajax.deleteSlot');
/*Slots End*/

/*Appointments*/
Route::resource('dashboard/doctor/appointments','Doctor\AppointmentsController');
Route::get('/dashboard/doctor/appointment/{appointment}/accept','Doctor\AppointmentsController@accept')->name('appointment.accept');
Route::get('/dashboard/doctor/appointment/{appointment}/reject','Doctor\AppointmentsController@reject')->name('appointment.reject');
Route::post('/get-chats-appointments','Doctor\AppointmentsController@getChatsAppointments')->name('get-chats-appointments');
Route::post('/get-previous-appointments','Doctor\AppointmentsController@getPreviousAppointments')->name('get-previous-appointments');
Route::post('/get-new-appointments','Doctor\AppointmentsController@getNewAppointments')->name('get-new-appointments');

Route::post('/dashboard/doctor/appointment/{appointment}/generatePdf','DynamicPDFController@generatePdf');

/*Appointments End*/

/* Dashboard Doctors */
Route::get('/dashboard/doctor/basic-details', 'Doctor\DoctorsController@index')->name('doctor.basic-details');
Route::get('/registerUser','Auth\RegisterController@registerUser')->name('home.registerUser');
Route::get('/registerDoctor','Auth\RegisterController@registerDoctor')->name('home.registerDoctor');
Route::post('/dashboard/doctor/medical-details', 'Doctor\DoctorsController@setBasicDetails')->name('doctor.medical-details');
Route::post('/dashboard/doctor/education', 'Doctor\DoctorsController@setEducation')->name('doctor.education');
Route::post('/dashboard/doctor/establishment', 'Doctor\DoctorsController@setEstablishment')->name('doctor.establishment');
Route::post('/dashboard/doctor/completed-profile', 'Doctor\DoctorsController@createDoctor')->name('doctor.completed');
Route::get('/dashboard/doctors',function(){
    return view('doctor.dashboard.basic-details');
});

/* Dashboard Doctors */

Route::get('/dashboard/user','User\UsersController@index')->name('user.dashboard.profile');
Route::get('/dashboard/user/{user}/edit','User\UsersController@editUser')->name('user.edit');
Route::put('/dashboard/user/update','User\UsersController@updateUserData')->name('user.updateData');

Route::post('doctor\getDoctors','User\DoctorsController@getDoctors')->name('ajax.getDoctors');

/* Dashboard users */


/*Chat routes*/
Route::get('/chats/chat',function(){
    return view('chats.chat');
});

Route::get('/receive',function(){

    $users = [];
    $arr = [];
    $appointments = auth()->user()->doctor->appointments;
    foreach($appointments as $appointment){
        $user = $appointment->user()->where($arr)->first();
        if($user)
            $users[] = $user;
        $arr[] = ['id','!=',$appointment->user->id];
    }
    return view('chat.receive',compact([
        'users'
    ]));
})->name('receive');
Route::get('/send',function(){
    $users = [];
    $arr = [];
    $appointments = auth()->user()->appointments;
    foreach($appointments as $appointment){
        $user = $appointment->doctor->user()->where($arr)->first();
        if($user)
            $users[] = $user;
        $arr[] = ['id','!=',$appointment->doctor->user->id];
    }
    return view('chat.send',compact([
        'users'
    ]));
})->name('send');

Route::post('/setchat','ChatsController@setChat')->name('chat.set');
Route::post('/send-chat','ChatsController@send')->name('chat.send');
Route::post('/receive-chat','ChatsController@received')->name('chat.received');
Route::post('/chat-update','ChatsController@chatUpdate')->name('chat.update');

Route::resource('document','User\MedicalRecordsController');

Route::post('document/updateData','User\MedicalRecordsController@updateData')->name('document.updateData');
Route::delete('document/destroyDocument/{medicalrecord}', 'User\MedicalRecordsController@destroyDocument')->name('document.destroyDocument');

/*Chat Routes*/



Route::get('/prescription', 'DynamicPDFController@index');
// Route::get('/dynamic_pdf', 'DynamicPDFController@index');
Route::get('/dynamic_pdf/pdf/', 'DynamicPDFController@pdf');
Route::post('/temp-pre', 'DynamicPDFController@index');

// Route::get('/prescription-form', 'DynamicPDFController@pf');
Route::get('/prescription-form',function(){
    return view('doctor.appointments.prescription-form',compact([

    ]));
});
Route::get('dashboard/user/slots','User\SlotsController@index')->name('user.appointments.index');
Route::get('dashboard/user/prescription','User\DoctorsController@showPrescriptions')->name('user.prescription');
Route::get('dashboard/user/orders','User\PharmaciesController@showOrders')->name('user.orders');

Route::post('/get-user','User\UsersController@getUser')->name('get-user');

/*pharma dashbaord*/
Route::delete('/dashboard/pharma/categories/destroy/{category}', 'Pharma\CategoriesController@destroy');
Route::delete('/dashboard/pharma/subcategories/destroy/{subcategory}', 'Pharma\SubcategoriesController@destroy');
Route::get('/dashboard/pharma/products/accept/{product}','Pharma\ProductsController@accept')->name('products.accept');
Route::get('/dashboard/pharma/products/reject/{product}','Pharma\ProductsController@reject')->name('products.reject');
Route::get('/dashboard/pharma/products/remove/{product}','Pharma\ProductsController@remove')->name('products.remove');
Route::get('/dashboard/pharma/category/{category}','Pharma\ProductsController@manageCategory')->name('products.manageCategory');
Route::get('/dashboard/pharma/subcategory/{subcategory}','Pharma\ProductsController@manageSubcategory')->name('products.manageSubcategory');

Route::resource('dashboard/pharma/products','Pharma\ProductsController');
Route::resource('dashboard/pharma/coupons','Pharma\CouponsController');
Route::resource('dashboard/pharma/categories','Pharma\CategoriesController');
Route::resource('dashboard/pharma/subcategories','Pharma\SubcategoriesController');
Route::get('/dashboard/pharma',function(){
    return view('pharma.dashboard.index');
})->name('pharma.dashboard');



Route::get('dashboard/pharma/manufacturerRequest','Pharma\ManufacturersController@index')->name('manufacturer.requests');

app/Pharma.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pharma extends Model
{
    protected $guarded = [];
    protected $table = "pharma";
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Pharma/CategoriesController.php
<?php

namespace App\Http\Controllers\Pharma;


use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use App\Category;
use App\Http\Requests\Pharma\CreateCategoryRequest;
use App\Http\Requests\Pharma\UpdateCategoryRequest;

class CategoriesController extends Controller
{
    public function index()
    {
        $categories = Category::latest()->get();
        $i = 1;
        return view('pharma.dashboard.categories.manage',compact([
            'categories',
            'i'
        ]));
    }

    public function create()
    {
        return view('pharma.dashboard.categories.create');
    }

    public function store(CreateCategoryRequest $request)
    {
        $category = Category::create([
            'name'=>$request->name
        ]);
        session()->flash('success','Category Added Successfully!');
        return redirect(route('categories.index'));
    }


    public function show(Category $category)
    {
        //
    }

    public function edit(Category $category)
    {
        return view('pharma.dashboard.categories.edit',compact([
            'category'
        ]));
    }

    public function update(UpdateCategoryRequest $request, Category $category)
    {
        $data = $request->only(['name']);
        $category->update($data);
        // dd($category);
        session()->flash('success','Category Updated Successfully!');
        return redirect(route('categories.index'));
    }


    public function destroy(Category $category)
    {
        $category = Category::where("id",$category->id);
        $category->forceDelete();
        session()->flash('success','Category Deleted Successfully');
        return redirect()->back();
    }

    public function viewCategoryProducts($category){
        // dd($category);
        $categories = Category::all();
        $singleCategory = Category::where('id',$category)->first();
        $subCategories = $singleCategory->subcategories()->get();
        $products = $singleCategory->products()->where('status','accept')->get();
        $isInCart = false;
        $quantity = 1;

        return view('pharma.category',compact([
            'products','subCategories','categories','singleCategory','isInCart','quantity'
        ]));
    }


}

app/Http/Controllers/Pharma/CouponsController.php
<?php

namespace App\Http\Controllers\Pharma;
use App\Http\Requests\Pharma\CreateCouponRequest;
use App\Http\Requests\Pharma\UpdateCouponRequest;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Coupon;

class CouponsController extends Controller
{
    public function index()
    {
        $coupons = Coupon::orderby('valid_till','desc')->get();
        $i = 1;
        return view('pharma.dashboard.coupons.manage',compact([
            'coupons',
            'i'
        ]));
    }

    public function create()
    {
        return view('pharma.dashboard.coupons.create');
    }

    public function edit(Coupon $coupon)
    {
        return view('pharma.dashboard.coupons.edit',compact([
            'coupon'
        ]));
    }

    public function store(CreateCouponRequest $request)
    {
        $coupon = Coupon::create([
            'code'=>$request->code,
            'min_amount'=>$request->min_amount,
            'valid_till'=>$request->valid_till,
            'max_discount'=>$request->max_discount
        ]);
        return redirect()->route('coupons.index');
    }

    public function update(UpdateCouponRequest $request, Coupon $coupon)
    {
        $data = $request->only(['code','min_amount','max_discount','valid_till']);
        $coupon->update($data);
        session()->flash('success','Coupon Updated Successfully!');
        return redirect(route('coupons.index'));
    }

    public function check(Request $request){
        $presentCoupon = Coupon::where('code',$request->coupon)->first();
        // dd($request->coupon);
        if($presentCoupon){
            $user = $presentCoupon->users()->where('user_id',auth()->user()->id)->first();

            if($user){
                return json_encode(['status'=>false,'reason'=>'Coupon already used!']);
            }
            // auth()->user()->coupons()->attach($presentCoupon->id);
            if($request->amount>=$presentCoupon->min_amount){
                session()->put('coupon',$presentCoupon->code);
                return json_encode(['status'=>true,'coupon'=>$presentCoupon]);
            }else{
                return json_encode(['status'=>true,'reason'=>'Not Sufficient Amount!']);
            }
        }
        return json_encode(['status'=>false,'reason'=>'Coupon not present!']);

    }
}

app/Http/Controllers/Pharma/ManufacturersController.php
<?php

namespace App\Http\Controllers\Pharma;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class ManufacturersController extends Controller
{
    public function index()
    {
        $users = User::where('role','temp_manufacturer')->orWhere('role','manufacturer')->get();
        return view('pharma.dashboard.manufacturer.manage-manufacturer',compact(['users']));
    }
    public function accept(Request $request,User $user)
    {
        if($user->password){
            $user->update([
                'role'=>'manufacturer'
            ]);
        }else{
            $user->update([
                'role'=>'manufacturer',
                'password'=>Hash::make('PractoManufacturer@12345')
            ]);
        }
        return redirect()->back();
    }
    public function reject(Request $request,User $user)
    {
        //$user->manufacturer->delete();
        $user->update([
            'role'=>'user'
        ]);
        return redirect()->back();
    }
}

resources/views/pharma/dashboard/_header.blade.php
<header class="header black-bg">
      <div class="sidebar-toggle-box">
        <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
      </div>
      <!--logo start-->
      <a href="" class="logo"><b>PRAC<span>TO</span></b></a>
      <!--logo end-->
      <div class="nav notify-row" id="top_menu">
        <!--  notification start -->
        <ul class="nav top-menu">
          <!-- settings start -->
          <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="index.html#">
              <i class="fa fa-tasks"></i>
              <span class="badge bg-theme">4</span>
              </a>
            <ul class="dropdown-menu extended tasks-bar">
              <div class="notify-arrow notify-arrow-green"></div>
              <li>
                <p class="green">You have 4 pending tasks</p>
              </li>
              <li>
                <a href="index.html#">
                  <div class="task-info">
                    <div class="desc">Dashio Admin Panel</div>
                    <div class="percent">40%</div>
                  </div>
                  <div class="progress progress-striped">
                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                      <span class="sr-only">40% Complete (success)</span>
                    </div>
                  </div>
                </a>
              </li>
              <li>
                <a href="index.html#">
                  <div class="task-info">
                    <div class="desc">Database Update</div>
                    <div class="percent">60%</div>
                  </div>
                  <div class="progress progress-striped">
                    <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                      <span class="sr-only">60% Complete (warning)</span>
                    </div>
                  </div>
                </a>
              </li>
              <li>
                <a href="index.html#">
                  <div class="task-info">
                    <div class="desc">Product Development</div>
                    <div class="percent">80%</div>
                  </div>
                  <div class="progress progress-striped">
                    <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                      <span class="sr-only">80% Complete</span>
                    </div>
                  </div>
                </a>
              </li>
              <li>
                <a href="index.html#">
                  <div class="task-info">
                    <div class="desc">Payments Sent</div>
                    <div class="percent">70%</div>
                  </div>
                  <div class="progress progress-striped">
                    <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: 70%">
                      <span class="sr-only">70% Complete (Important)</span>
                    </div>
                  </div>
                </a>
              </li>
              <li class="external">
                <a href="#">See All Tasks</a>
              </li>
            </ul>
          </li>
          <!-- settings end -->
          <!-- inbox dropdown start-->
          <li id="header_inbox_bar" class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="index.html#">
              <i class="fa fa-envelope-o"></i>
              <span class="badge bg-theme">5</span>
              </a>
            <ul class="dropdown-menu extended inbox">
              <div class="notify-arrow notify-arrow-green"></div>
              <li>
                <p class="green">You have 5 new messages</p>
              </li>
              <li>
                <a href="index.html#">
                  <span class="photo"><img alt="avatar" src="{{asset('dashboard/img/ui-zac.jpg')}}"></span>
                  <span class="subject">
                  <span class="from">Zac Snider</span>
                  <span class="time">Just now</span>
                  </span>
                  <span class="message">
                  Hi mate, how is everything?
                  </span>
                  </a>
              </li>
              <li>
                <a href="index.html#">
                  <span class="photo"><img alt="avatar" src="{{asset('dashboard/img/ui-divya.jpg')}}"></span>
                  <span class="subject">
                  <span class="from">Divya Manian</span>
                  <span class="time">40 mins.</span>
                  </span>
                  <span class="message">
                  Hi, I need your help with this.
                  </span>
                  </a>
              </li>
              <li>
                <a href="index.html#">
                  <span class="photo"><img alt="avatar" src="{{asset('dashboard/img/ui-danro.jpg')}}"></span>
                  <span class="subject">
                  <span class="from">Dan Rogers</span>
                  <span class="time">2 hrs.</span>
                  </span>
                  <span class="message">
                  Love your new Dashboard.
                  </span>
                  </a>
              </li>
              <li>
                <a href="index.html#">
                  <span class="photo"><img alt="avatar" src="{{asset('dashboard/img/ui-sherman.jpg')}}"></span>
                  <span class="subject">
                  <span class="from">Dj Sherman</span>
                  <span class="time">4 hrs.</span>
                  </span>
                  <span class="message">
                  Please, answer asap.
                  </span>
                  </a>
              </li>
              <li>
                <a href="index.html#">See all messages</a>
              </li>
            </ul>
          </li>
          <!-- inbox dropdown end -->
          <!-- notification dropdown start-->
          <li id="header_notification_bar" class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="index.html#">
              <i class="fa fa-bell-o"></i>
              <span class="badge bg-warning" id="unread">{{auth()->user()->unreadNotification()}}</span>
              </a>
            <ul class="dropdown-menu extended notification" id="doc-nav-notification">
                <div class="notify-arrow notify-arrow-yellow"></div>
                @foreach (auth()->user()->notificationReceived->take(5) as $notify)
                    <li>
                        <a href="">
                            <span class="label label-danger"><i class="fa fa-bolt"></i></span>
                            {{$notify->type->message}}
                        </a>
                    </li>
                @endforeach
                <li>
                    <p class="yellow">You have <span id="total-notify">{{auth()->user()->notificationReceived->count()>5 ? '5' : auth()->user()->notificationReceived->count()}}</span> notifications</p>
                </li>
            </ul>
          </li>
          <!-- notification dropdown end -->
        </ul>
        <!--  notification end -->
      </div>
      <div class="top-menu">
        <ul class="nav pull-right top-menu">
          <li><a class="logout" href="login.html">Logout</a></li>
        </ul>
      </div>
    </header>

resources/views/pharma/dashboard/index.blade.php
@extends('pharma.dashboard.layout')
@section('title','Practo | Pharma Dashboard')
@section('dashboard-title','Welcome back!')

@section('main-content')
   <div class="portfolio">
    <div class="container">
        <div class="row">
          <h4>Hello! Welcome to Practo Pharmacy Management</h4>  
        </div>
    </div>
    </div>
@endsection

resources/views/pharma/dashboard/message.blade.php
<div class="row">
    <div class="col-md-12">
        @if(session()->has('success'))
            <div class="alert alert-success alert-dismissable fade show" role="alert">
                {{session()->get('success')}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif

        @if(session()->has('error'))
        <div class="alert alert-danger alert-dismissable fade show" role="alert">
                {{session()->get('error')}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @endif
        
    </div>
</div>

resources/views/pharma/dashboard/sidebar.blade.php
<aside>
      <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu" id="nav-accordion">

        <li class="sub-menu mt">
            <a href="{{route('manufacturer.requests')}}">
              <i class="fa fa-users"></i>
              <span>Manufacturers</span>
              </a>
          </li> 
          <li class="sub-menu">
            <a href="{{route('products.index')}}">
              <i class="fa fa-th"></i>
              <span>Products</span>
              </a>
          </li>
          <li class="sub-menu ">
            <a href="javascript:;">
              <i class="fa fa-cog"></i>
              <span>Categories</span>
              </a>
            <ul class="sub">
              <li><a href="{{route('categories.create')}}">Add Catgeory</a></li>
              <li><a href="{{route('categories.index')}}">Manage Categories</a></li>
            </ul>
          </li>
          <li class="sub-menu">
            <a href="{{route('subcategories.index')}}">
              <i class="fa fa-pencil"></i>
              <span>Subcategories</span>
              </a>
          </li>
        
          <li class="sub-menu">
            <a href="javascript:;">
              <i class="fa fa-barcode"></i>
              <span>Coupons</span>
              </a>
            <ul class="sub">
              <li><a href="{{route('coupons.create')}}">Add Coupon</a></li>
              <li><a href="{{route('coupons.index')}}">Manage Coupons</a></li>
            </ul>
          </li>
        </ul>
        <!-- sidebar menu end-->
      </div>
    </aside>