routes/web.php
<?php

use App\Coupon;
use App\Doctor;
use App\Http\Controllers\DoctorsController;
use App\Http\Controllers\HomeController;
use App\Product;
use App\User;
use Illuminate\Http\Request;


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*Header Routes*/

Route::get('/', function () {
    $section = 'consult';
    return view('home.index',compact([
        'section'
    ]));
})->name('index');



//User Routes
Route::post('user/address','AddressController@store')->name('users.address');
Route::get('/doctors', function () {
    $doctors = Doctor::all();
    $section = 'doctors';
    return view('user.findDoctor.doctors',compact([
        'doctors',
        'section'
    ]));
})->name('doctors.findDoctors');

Route::get('/pharma', function () {
    $products = Product::where('status','accept')->get()->take(5);

    $section = 'pharma';
    return view('user.pharma.index',compact([
        'section','products'
    ]));
})->name('pharma.index');


/*End of Header Routes*/


Route::get('/user/consult','User\UsersController@createChatAppointment')->name('users.chatAppointment');
Route::post('/user/consult/bookAppointment','User\UsersController@bookChatAppointment')->name('users.bookChatAppointment');

Route::post('/user/consult/checkChatAppointment','User\UsersController@checkChatBookedAppointment')->name('users.checkChatBookedAppointment');


Route::get('/pharma/single-product', function () {
    return view('user.pharma.single_product');
});

Route::get('/order/cart','CartController@index');
// Route::get('/order/checkout', function () {
//     return view('pharma.dashboard.cart.checkout');
// });
Route::get('/order/checkout','CartController@checkout')->name('cart.checkout');

// Route::get('/order/checkout', function () {
//     return view('pharma.dashboard.cart.checkout');
// });

Route::resource('doctor', 'User\DoctorsController');
Route::post('user\getCurrentLocation','User\UsersController@getCurrentLocation')->name('ajax.getCurrentLocation');
Route::post('doctor\getDoctors','User\DoctorsController@getDoctors')->name('ajax.getDoctors');

/*Login controller routes*/

Auth::routes();

Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::post('/getotp', 'Auth\RegisterController@generateMessage')->name('register.sendotp');
Route::post('/getotpforuser', 'Auth\RegisterController@generateMessageForUser')->name('sendotpForuser');
Route::get('/resendotp', 'Auth\RegisterController@resendOTP')->name('resend');
Route::post('/verifyotp', 'Auth\RegisterController@verifyOtp')->name('verifyotp');
Route::get('/home', 'HomeController@index')->name('home');

/*Login controller routes*/

Route::get('/doctors/{doctor}/appointment/{slot}/{type}','User\DoctorsController@confirmAppointment')->name('doctors.confirmAppointment');
Route::post('/doctors/{doctor}/appointment/{slot}/store/p','User\DoctorsController@bookPersonalAppointment')->name('doctors.bookPersonalAppointment');
Route::post('/doctors/{doctor}/appointment/{slot}/store/o','User\DoctorsController@bookOthersAppointment')->name('doctors.bookOthersAppointment');

Route::post('/doctor/getslot','User\DoctorsController@fetchNextDaySlots')->name('ajax.fetchNextDaySlots');
Route::get('/doctors/{doctor}','User\DoctorsController@show')->name('doctors.show');

Route::get('/chats/chat',function(){
    return view('chats.chat');
});

Route::get('/dashboard/doctor',function(){
    $section = "profile";
    return view('doctor.dashboard.index',compact([
        'section'
    ]));
})->name('doctor.dashboard');

/*Slots*/
Route::get('dashboard/doctor/slots/{SlotDate}/edit','Doctor\SlotsController@edit')->name('slot.edit');
Route::resource('dashboard/doctor/slots','Doctor\SlotsController')->except('edit','update','destroy');
Route::put('dashboard/doctor/slots/{SlotDate}/update','Doctor\SlotsController@update')->name('slot.update');
Route::post('dashboard/doctor/slots/delete','Doctor\SlotsController@destroy')->name('ajax.deleteSlot');
/*Slots End*/

/*Appointments*/
Route::resource('dashboard/doctor/appointments','Doctor\AppointmentsController');
Route::get('/dashboard/doctor/appointment/{appointment}/accept','Doctor\AppointmentsController@accept')->name('appointment.accept');
Route::get('/dashboard/doctor/appointment/{appointment}/reject','Doctor\AppointmentsController@reject')->name('appointment.reject');
Route::post('/get-chats-appointments','Doctor\AppointmentsController@getChatsAppointments')->name('get-chats-appointments');
Route::post('/get-previous-appointments','Doctor\AppointmentsController@getPreviousAppointments')->name('get-previous-appointments');
Route::post('/get-new-appointments','Doctor\AppointmentsController@getNewAppointments')->name('get-new-appointments');

Route::post('/dashboard/doctor/appointment/{appointment}/generatePdf','DynamicPDFController@generatePdf');

/*Appointments End*/

/* Dashboard Doctors */
Route::get('/dashboard/doctor/basic-details', 'Doctor\DoctorsController@index')->name('doctor.basic-details');
Route::get('/registerUser','Auth\RegisterController@registerUser')->name('home.registerUser');
Route::get('/registerDoctor','Auth\RegisterController@registerDoctor')->name('home.registerDoctor');
Route::post('/dashboard/doctor/medical-details', 'Doctor\DoctorsController@setBasicDetails')->name('doctor.medical-details');
Route::post('/dashboard/doctor/education', 'Doctor\DoctorsController@setEducation')->name('doctor.education');
Route::post('/dashboard/doctor/establishment', 'Doctor\DoctorsController@setEstablishment')->name('doctor.establishment');
Route::post('/dashboard/doctor/completed-profile', 'Doctor\DoctorsController@createDoctor')->name('doctor.completed');
Route::get('/dashboard/doctors',function(){
    return view('doctor.dashboard.basic-details');
});

/* Dashboard Doctors */

Route::get('/dashboard/user','User\UsersController@index')->name('user.dashboard.profile');
Route::get('/dashboard/user/{user}/edit','User\UsersController@editUser')->name('user.edit');
Route::put('/dashboard/user/update','User\UsersController@updateUserData')->name('user.updateData');

Route::post('doctor\getDoctors','User\DoctorsController@getDoctors')->name('ajax.getDoctors');

/* Dashboard users */


/*Chat routes*/
Route::get('/chats/chat',function(){
    return view('chats.chat');
});

Route::get('/receive',function(){

    $users = [];
    $arr = [];
    $appointments = auth()->user()->doctor->appointments;
    foreach($appointments as $appointment){
        $user = $appointment->user()->where($arr)->first();
        if($user)
            $users[] = $user;
        $arr[] = ['id','!=',$appointment->user->id];
    }
    return view('chat.receive',compact([
        'users'
    ]));
})->name('receive');
Route::get('/send',function(){
    $users = [];
    $arr = [];
    $appointments = auth()->user()->appointments;
    foreach($appointments as $appointment){
        $user = $appointment->doctor->user()->where($arr)->first();
        if($user)
            $users[] = $user;
        $arr[] = ['id','!=',$appointment->doctor->user->id];
    }
    return view('chat.send',compact([
        'users'
    ]));
})->name('send');

Route::post('/setchat','ChatsController@setChat')->name('chat.set');
Route::post('/send-chat','ChatsController@send')->name('chat.send');
Route::post('/receive-chat','ChatsController@received')->name('chat.received');
Route::post('/chat-update','ChatsController@chatUpdate')->name('chat.update');

Route::resource('document','User\MedicalRecordsController');

Route::post('document/updateData','User\MedicalRecordsController@updateData')->name('document.updateData');
Route::delete('document/destroyDocument/{medicalrecord}', 'User\MedicalRecordsController@destroyDocument')->name('document.destroyDocument');

/*Chat Routes*/



Route::get('/prescription', 'DynamicPDFController@index');
// Route::get('/dynamic_pdf', 'DynamicPDFController@index');
Route::get('/dynamic_pdf/pdf/', 'DynamicPDFController@pdf');
Route::post('/temp-pre', 'DynamicPDFController@index');

// Route::get('/prescription-form', 'DynamicPDFController@pf');
Route::get('/prescription-form',function(){
    return view('doctor.appointments.prescription-form',compact([

    ]));
});
Route::get('dashboard/user/slots','User\SlotsController@index')->name('user.appointments.index');
Route::get('dashboard/user/prescription','User\DoctorsController@showPrescriptions')->name('user.prescription');
Route::get('dashboard/user/orders','User\PharmaciesController@showOrders')->name('user.orders');

Route::post('/get-user','User\UsersController@getUser')->name('get-user');

/*pharma dashbaord*/
Route::delete('/dashboard/pharma/categories/destroy/{category}', 'Pharma\CategoriesController@destroy');
Route::delete('/dashboard/pharma/subcategories/destroy/{subcategory}', 'Pharma\SubcategoriesController@destroy');
Route::get('/dashboard/pharma/products/accept/{product}','Pharma\ProductsController@accept')->name('products.accept');
Route::get('/dashboard/pharma/products/reject/{product}','Pharma\ProductsController@reject')->name('products.reject');
Route::get('/dashboard/pharma/products/remove/{product}','Pharma\ProductsController@remove')->name('products.remove');
Route::get('/dashboard/pharma/category/{category}','Pharma\ProductsController@manageCategory')->name('products.manageCategory');
Route::get('/dashboard/pharma/subcategory/{subcategory}','Pharma\ProductsController@manageSubcategory')->name('products.manageSubcategory');

Route::resource('dashboard/pharma/products','Pharma\ProductsController');
Route::resource('dashboard/pharma/coupons','Pharma\CouponsController');
Route::resource('dashboard/pharma/categories','Pharma\CategoriesController');
Route::resource('dashboard/pharma/subcategories','Pharma\SubcategoriesController');
Route::get('/dashboard/pharma',function(){
    return view('pharma.dashboard.index');
})->name('pharma.dashboard');



Route::get('dashboard/pharma/manufacturerRequest','Pharma\ManufacturersController@index')->name('manufacturer.requests');

app/Http/Controllers/User/MedicalRecordsController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Medicalrecords;
use App\User;
use Illuminate\Http\Request;

class MedicalRecordsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::find(auth()->user()->id);
        return view('user.dashboard.medical-records',compact(['user']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request->file('img')){
            $image=$request->file('img')->store('documents');
            auth()->user()->documents()->create([
                'name'=>$request->name,
                'location'=>$image
            ]);
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Medicalrecords  $medicalrecords
     * @return \Illuminate\Http\Response
     */
    public function show(Medicalrecords $medicalrecords)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Medicalrecords  $medicalrecords
     * @return \Illuminate\Http\Response
     */
    public function edit(Medicalrecords $medicalrecords)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Medicalrecords  $medicalrecords
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Medicalrecords $medicalrecords)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Medicalrecords  $medicalrecords
     * @return \Illuminate\Http\Response
     */
    public function destroy(Medicalrecords $medicalrecords)
    {
        dd($medicalrecords);
        $medicalrecords->delete();
        return redirect()->back();
    }
    public function updateData(Request $request){
        $document = Medicalrecords::find($request->document_id);
        $image = $document->location;
        if($request->file('img')){
            $image = $request->file('img')->store('document');
        }
        $document->update([
            'name'=>$request->name,
            'location'=>$image
        ]);
        return redirect()->back();
    }

    public function destroyDocument(Medicalrecords $medicalrecord)
    {
        $medicalrecord->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/User/PharmaciesController.php
<?php

namespace App\Http\Controllers\User;

use App\Address;
use App\Http\Controllers\Controller;
use App\Order;
use App\Pharma;
use App\Product;
use Illuminate\Http\Request;

class PharmaciesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Pharma  $pharma
     * @return \Illuminate\Http\Response
     */
    public function show(Pharma $pharma)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Pharma  $pharma
     * @return \Illuminate\Http\Response
     */
    public function edit(Pharma $pharma)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Pharma  $pharma
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pharma $pharma)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Pharma  $pharma
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pharma $pharma)
    {
        //
    }
    public function showOrders(){
        $user = auth()->user();
        $orders = Order::where('user_id',$user->id)->get();
// dd($orders);
        foreach($orders as $order){
            $address = Address::where('id',$order->address_id)->first('address');
            // dd($address);
            $billingName= $order->billing_name;
            $email= $order->email;
            $products = $user->products;
            // dd($products);
            $productDetails = [];
            foreach($products as $product){
                // dd($product->pivot->count);
                $productDetail = [];
                $productDetail[] = $order->billing_name;
                $productDetail[] = $address->address;
                $productDetail[] = $product->name;
                $productDetail[] = $product->pivot->count;
                $productDetail[] = $product->price;
                $productDetail[] = $product->price * $product->pivot->count;

                $productDetails[] = $productDetail;

            }
        }
        return view('user.dashboard.orders.index', compact([
            'productDetails'
        ]));


    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
    public function getCurrentLocation(Request $request){
        // $ip = \Request::ip();
        //$ip = '43.231.238.110';
        //$data = \Location::get($ip);
       // return json_encode($data->cityName);
    }
}

resources/views/user/dashboard/edit-profile.blade.php
@extends('user.dashboard.layout')
@section('title','Practo | User')
@section('page-level-styles')
<style>
.card span{
 color:red;
 font-size:17px;
}
.btn{
    margin-top:1rem;
    padding:10px 45px;
    border-radius:0;
  }
</style>
@endsection
@section('dashboard-title'.'My profile')
@section('main-content')
    <form action="{{route('user.updateData')}}" method="POST">
        @csrf
        @method('PUT')
        <div class="col-md-12">
            <div class="card" style="box-shadow:none;margin-top:3rem">
                <div class="card-body">
                    <div class="col-md-6" style="border-right:solid 1px #51328C">
                        <div class="form-group col-md-6">
                            <label for="name">Name<span>*<span></label>
                            <input type="text"
                            value="{{$user->name}}"
                            class="form-control @error('name') is-invalid @enderror"
                            name="name" id="name">
                            @error('name')
                                <span class="text-danger">{{$errors->first('name')}}</span>
                            @enderror
                        </div>
                        <div class="form-group col-md-6">
                            <label for="age">Age<span>*<span></label>
                            <input type="number"
                            value="{{$user->age}}"
                            class="form-control @error('age') is-invalid @enderror"
                            name="age" id="age">
                            @error('age')
                                <span class="text-danger">{{$errors->first('age')}}</span>
                            @enderror
                        </div>
                        <div class="form-group col-md-12">
                            <label for="email">Email<span>*<span></label>
                            <input type="email"
                            value="{{$user->email}}"
                            class="form-control @error('email') is-invalid @enderror"
                            name="email" id="email">
                            @error('email')
                                <span class="text-danger">{{$errors->first('email')}}</span>
                            @enderror
                        </div>
                        <div class="form-group col-md-12">
                            <label for="password">Password<span>*<span></label>
                            <input type="password"
                            class="form-control @error('password') is-invalid @enderror" value=""
                            name="password" id="password">
                            @error('password')
                                <span class="text-danger">{{$errors->first('password')}}</span>
                            @enderror
                        </div>
                        <div class="form-group col-md-6">
                            <label for="phone_no">Phone Number<span>*<span></label>
                            <input type="number"
                            value="{{$user->phone_no}}"
                            class="form-control @error('phone_no') is-invalid @enderror"
                            name="phone_no" id="phone_no">
                            @error('phone_no')
                                <span class="text-danger">{{$errors->first('phone_no')}}</span>
                            @enderror
                        </div>
                        <div class="form-group col-md-6">
                            <label for="gender">Gender<span>*<span></label>
                            <select name="gender" id="gender" class="form-control">
                                <option class="form-control" value="male" {{($user->gender==null) ? '' : (($user->gender=='male') ? 'selected' : '')}}>Male</option>
                                <option class="form-control" value="female" {{($user->gender==null) ? '' : (($user->gender=='female') ? 'selected' : '')}}>Female</option>
                                <option class="form-control" value="other" {{($user->gender==null) ? '' : (($user->gender=='other') ? 'selected' : '')}}>Other</option>
                            </select>
                            @error('password')
                                <span class="text-danger">{{$errors->first('password')}}</span>
                            @enderror
                        </div>
                        <div class="form-group col-md-3">
                            <button type="submit" class="btn btn-primary">save</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/user/dashboard/medical-records.blade.php
@extends('user.dashboard.layout')
@section('title','Practo | User Dashboard')
@section('dashboard-title','My Medical Records')
@section('main-content')
    <div>
        <div class="" style="display: flex; flex-direction: row-reverse;">
            <div class="my-btn" style="margin-right: 20px" id="upload-img-btn">upload Documents</div>
        </div>
        <!--begin: Datatable -->
        <div class="adv-table" style="margin-top: 10px; margin-left:20px ; margin-right: 20px">
            <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="hidden-table-info">
                <thead>
                    <tr>
                        <th>Sr.No</th>
                        <th>Name</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                        $i=1;
                    ?>
                    @foreach ($user->documents as $document)
                        <tr>
                            <td><?=$i++?></td>
                            <td id="name-{{$document->id}}">{{$document->name}}</td>
                            <td class="d-flex">
                                <a class='edit-data btn btn-primary btn-sm ml-2' data-id="{{$document->id}}" class='btn btn-primary btn-sm' style="margin-right: 3px" href="#!"><i class='fa fa-pencil'></i></a>
                                {{-- <a class='btn btn-primary btn-sm ml-2' style="margin-right: 3px" href="{{route('document.destroy',$document->id)}}"><i class='fa fa-trash'></i></a> --}}
                                <form action="{{route('document.destroyDocument',$document->id)}}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-primary btn-sm mr-2" type="submit" style="margin-right: 5px; margin-left: 5px;"><i class='fa fa-trash'></i></button>
                                </form>
                                <a class='btn btn-primary btn-sm ml-4' alt="Download" href="{{asset('storage/'.$document->location)}}" download><i class="fa fa-download" aria-hidden="true"></i></a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <!--end: Datatable -->
    </div>

    {{-- upload document modal --}}

    <div id="card" class="d-none">
        <div class="wrapper">
            <div class="card-head">
                Upload Document
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <form action="{{route('document.store')}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('POST')
                            <div class="form-group col-md-12">
                                <label for="name">Name</label>
                                <input type="text" class="form-control" name="name" id="name" required>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="name">Uplaod</label>
                                <input type="file" class="form-control" name="img" id="img" required>
                            </div>
                            <button class="my-btn col-md-2" type="submit">save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="edit-card" class="d-none">
        <div class="wrapper">
            <div class="card-head">
                Upload Document
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <form action="{{route('document.updateData')}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('POST')
                            <div class="form-group col-md-12">
                                <input type="hidden" id="edit-document-id" name="document_id">
                                <label for="name">Name</label>
                                <input type="text" class="form-control" name="name" id="edit-name" required>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="name">Uplaod</label>
                                <input type="file" class="form-control" name="img" id="edit-img">
                            </div>
                            <button class="my-btn col-md-2" type="submit">save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('page-level-styles')
    <style>
        .d-flex{
            display: flex;
        }
        .d-none{
            display: none !important;
        }
        .d-inline-block{
            display: inline-block !important;
        }
    </style>
@endsection
@section('page-level-scripts')
    <script src="{{ asset('assets/doctors/js/plugin/datatables/datatables.bundle.js')}}" type="text/javascript"></script>
    <script>
        var oTable = $('#hidden-table-info').dataTable({
            "aoColumnDefs": [{
            "bSortable": false,
            "aTargets": [0]
            }],
            "aaSorting": [
            [0, 'asc']
            ]
        });

        $('#upload-img-btn').click(function(){
            $('#card').toggleClass('d-inline-block').toggleClass('d-block');
        });

        $('#card').click(function(){
            $('#card').toggleClass('d-inline-block').toggleClass('d-block');
        });
        $('#card .wrapper').click(function(e){
            e.stopPropagation();
        });
        $('#edit-card').click(function(){
            $('#edit-card').toggleClass('d-inline-block').toggleClass('d-block');
        });
        $('#edit-card .wrapper').click(function(e){
            e.stopPropagation();
        });

        $('.edit-data').click(function(){
            var documentID = $(this).data('id');
            var name = $('#name-'+documentID).html();
            $('#edit-name').val(name);
            $('#edit-document-id').val(documentID);
            $('#edit-card').toggleClass('d-inline-block').toggleClass('d-block');
        });
    </script>
@endsection

resources/views/user/dashboard/profile.blade.php
@extends('user.dashboard.layout')
@section('title','Practo | User')
@section('page-level-styles')
<style>
.card span{
 color:red;
 font-size:17px;
}
.btn{
    margin-top:1rem;
    padding:10px 45px;
    border-radius:0;
  }
</style>
@endsection
@section('dashboard-title')
    <div class="col-md-12">
        <div class="col-md-10">My profile</div>
        <a href="{{route('user.edit',$user->id)}}" class="btn btn-primary">Edit / Add Data</a>
    </div>
@endsection
@section('main-content')
    <div class="col-md-12">
        <div class="card" style="box-shadow:none;margin-top:3rem">
            <div class="card-body">
                <div class="col-md-6" style="border-right:solid 1px #51328C">
                    <div class="form-group col-md-12">
                        <label for="fullname">Full Name<span>*<span></label>
                        <input type="text" required
                        value="{{$user->name}}"
                        class="form-control" disabled
                        name="fullname" id="fullname" disabled>
                    </div>
                    <div class="form-group col-md-12">
                        <label for="email">Email<span>*<span></label>
                        <input type="email" required
                        value="{{$user->email}}"
                        class="form-control"
                        name="email" id="email" disabled>
                    </div>
                    <div class="form-group col-md-12">
                        <label for="password">Password<span>*<span></label>
                        <input type="password" required
                        class="form-control" value="{{ $user->password }}"
                        name="password" id="password" disabled>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="phone_no">Phone Number<span>*<span></label>
                        <input type="number" disabled
                        value="{{$user->phone_no}}"
                        class="form-control"
                        name="phone_no" id="phone_no" disabled>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="gender">Gender<span>*<span></label>
                        <input type="text" class="form-control" id="gender" name="gender" value="{{$user->gender == null ? '':$user->gender}}" disabled>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection