routes/web.php
<?php

use App\Coupon;
use App\Doctor;
use App\Http\Controllers\DoctorsController;
use App\Http\Controllers\HomeController;
use App\Product;
use App\User;
use Illuminate\Http\Request;


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*Header Routes*/

Route::get('/', function () {
    $section = 'consult';
    return view('home.index',compact([
        'section'
    ]));
})->name('index');



//User Routes
Route::post('user/address','AddressController@store')->name('users.address');
Route::get('/doctors', function () {
    $doctors = Doctor::all();
    $section = 'doctors';
    return view('user.findDoctor.doctors',compact([
        'doctors',
        'section'
    ]));
})->name('doctors.findDoctors');

Route::get('/pharma', function () {
    $products = Product::where('status','accept')->get()->take(5);

    $section = 'pharma';
    return view('user.pharma.index',compact([
        'section','products'
    ]));
})->name('pharma.index');


/*End of Header Routes*/


Route::get('/user/consult','User\UsersController@createChatAppointment')->name('users.chatAppointment');
Route::post('/user/consult/bookAppointment','User\UsersController@bookChatAppointment')->name('users.bookChatAppointment');

Route::post('/user/consult/checkChatAppointment','User\UsersController@checkChatBookedAppointment')->name('users.checkChatBookedAppointment');


Route::get('/pharma/single-product', function () {
    return view('user.pharma.single_product');
});

Route::get('/order/cart','CartController@index');
// Route::get('/order/checkout', function () {
//     return view('pharma.dashboard.cart.checkout');
// });
Route::get('/order/checkout','CartController@checkout')->name('cart.checkout');

// Route::get('/order/checkout', function () {
//     return view('pharma.dashboard.cart.checkout');
// });

Route::resource('doctor', 'User\DoctorsController');
Route::post('user\getCurrentLocation','User\UsersController@getCurrentLocation')->name('ajax.getCurrentLocation');
Route::post('doctor\getDoctors','User\DoctorsController@getDoctors')->name('ajax.getDoctors');

/*Login controller routes*/

Auth::routes();

Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::post('/getotp', 'Auth\RegisterController@generateMessage')->name('register.sendotp');
Route::post('/getotpforuser', 'Auth\RegisterController@generateMessageForUser')->name('sendotpForuser');
Route::get('/resendotp', 'Auth\RegisterController@resendOTP')->name('resend');
Route::post('/verifyotp', 'Auth\RegisterController@verifyOtp')->name('verifyotp');
Route::get('/home', 'HomeController@index')->name('home');

/*Login controller routes*/

Route::get('/doctors/{doctor}/appointment/{slot}/{type}','User\DoctorsController@confirmAppointment')->name('doctors.confirmAppointment');
Route::post('/doctors/{doctor}/appointment/{slot}/store/p','User\DoctorsController@bookPersonalAppointment')->name('doctors.bookPersonalAppointment');
Route::post('/doctors/{doctor}/appointment/{slot}/store/o','User\DoctorsController@bookOthersAppointment')->name('doctors.bookOthersAppointment');

Route::post('/doctor/getslot','User\DoctorsController@fetchNextDaySlots')->name('ajax.fetchNextDaySlots');
Route::get('/doctors/{doctor}','User\DoctorsController@show')->name('doctors.show');

Route::get('/chats/chat',function(){
    return view('chats.chat');
});

Route::get('/dashboard/doctor',function(){
    $section = "profile";
    return view('doctor.dashboard.index',compact([
        'section'
    ]));
})->name('doctor.dashboard');

/*Slots*/
Route::get('dashboard/doctor/slots/{SlotDate}/edit','Doctor\SlotsController@edit')->name('slot.edit');
Route::resource('dashboard/doctor/slots','Doctor\SlotsController')->except('edit','update','destroy');
Route::put('dashboard/doctor/slots/{SlotDate}/update','Doctor\SlotsController@update')->name('slot.update');
Route::post('dashboard/doctor/slots/delete','Doctor\SlotsController@destroy')->name('ajax.deleteSlot');
/*Slots End*/

/*Appointments*/
Route::resource('dashboard/doctor/appointments','Doctor\AppointmentsController');
Route::get('/dashboard/doctor/appointment/{appointment}/accept','Doctor\AppointmentsController@accept')->name('appointment.accept');
Route::get('/dashboard/doctor/appointment/{appointment}/reject','Doctor\AppointmentsController@reject')->name('appointment.reject');
Route::post('/get-chats-appointments','Doctor\AppointmentsController@getChatsAppointments')->name('get-chats-appointments');
Route::post('/get-previous-appointments','Doctor\AppointmentsController@getPreviousAppointments')->name('get-previous-appointments');
Route::post('/get-new-appointments','Doctor\AppointmentsController@getNewAppointments')->name('get-new-appointments');

Route::post('/dashboard/doctor/appointment/{appointment}/generatePdf','DynamicPDFController@generatePdf');

/*Appointments End*/

/* Dashboard Doctors */
Route::get('/dashboard/doctor/basic-details', 'Doctor\DoctorsController@index')->name('doctor.basic-details');
Route::get('/registerUser','Auth\RegisterController@registerUser')->name('home.registerUser');
Route::get('/registerDoctor','Auth\RegisterController@registerDoctor')->name('home.registerDoctor');
Route::post('/dashboard/doctor/medical-details', 'Doctor\DoctorsController@setBasicDetails')->name('doctor.medical-details');
Route::post('/dashboard/doctor/education', 'Doctor\DoctorsController@setEducation')->name('doctor.education');
Route::post('/dashboard/doctor/establishment', 'Doctor\DoctorsController@setEstablishment')->name('doctor.establishment');
Route::post('/dashboard/doctor/completed-profile', 'Doctor\DoctorsController@createDoctor')->name('doctor.completed');
Route::get('/dashboard/doctors',function(){
    return view('doctor.dashboard.basic-details');
});

/* Dashboard Doctors */

Route::get('/dashboard/user','User\UsersController@index')->name('user.dashboard.profile');
Route::get('/dashboard/user/{user}/edit','User\UsersController@editUser')->name('user.edit');
Route::put('/dashboard/user/update','User\UsersController@updateUserData')->name('user.updateData');

Route::post('doctor\getDoctors','User\DoctorsController@getDoctors')->name('ajax.getDoctors');

/* Dashboard users */


/*Chat routes*/
Route::get('/chats/chat',function(){
    return view('chats.chat');
});

Route::get('/receive',function(){

    $users = [];
    $arr = [];
    $appointments = auth()->user()->doctor->appointments;
    foreach($appointments as $appointment){
        $user = $appointment->user()->where($arr)->first();
        if($user)
            $users[] = $user;
        $arr[] = ['id','!=',$appointment->user->id];
    }
    return view('chat.receive',compact([
        'users'
    ]));
})->name('receive');
Route::get('/send',function(){
    $users = [];
    $arr = [];
    $appointments = auth()->user()->appointments;
    foreach($appointments as $appointment){
        $user = $appointment->doctor->user()->where($arr)->first();
        if($user)
            $users[] = $user;
        $arr[] = ['id','!=',$appointment->doctor->user->id];
    }
    return view('chat.send',compact([
        'users'
    ]));
})->name('send');

Route::post('/setchat','ChatsController@setChat')->name('chat.set');
Route::post('/send-chat','ChatsController@send')->name('chat.send');
Route::post('/receive-chat','ChatsController@received')->name('chat.received');
Route::post('/chat-update','ChatsController@chatUpdate')->name('chat.update');

Route::resource('document','User\MedicalRecordsController');

Route::post('document/updateData','User\MedicalRecordsController@updateData')->name('document.updateData');
Route::delete('document/destroyDocument/{medicalrecord}', 'User\MedicalRecordsController@destroyDocument')->name('document.destroyDocument');

/*Chat Routes*/



Route::get('/prescription', 'DynamicPDFController@index');
// Route::get('/dynamic_pdf', 'DynamicPDFController@index');
Route::get('/dynamic_pdf/pdf/', 'DynamicPDFController@pdf');
Route::post('/temp-pre', 'DynamicPDFController@index');

// Route::get('/prescription-form', 'DynamicPDFController@pf');
Route::get('/prescription-form',function(){
    return view('doctor.appointments.prescription-form',compact([

    ]));
});
Route::get('dashboard/user/slots','User\SlotsController@index')->name('user.appointments.index');
Route::get('dashboard/user/prescription','User\DoctorsController@showPrescriptions')->name('user.prescription');
Route::get('dashboard/user/orders','User\PharmaciesController@showOrders')->name('user.orders');

Route::post('/get-user','User\UsersController@getUser')->name('get-user');

/*pharma dashbaord*/
Route::delete('/dashboard/pharma/categories/destroy/{category}', 'Pharma\CategoriesController@destroy');
Route::delete('/dashboard/pharma/subcategories/destroy/{subcategory}', 'Pharma\SubcategoriesController@destroy');
Route::get('/dashboard/pharma/products/accept/{product}','Pharma\ProductsController@accept')->name('products.accept');
Route::get('/dashboard/pharma/products/reject/{product}','Pharma\ProductsController@reject')->name('products.reject');
Route::get('/dashboard/pharma/products/remove/{product}','Pharma\ProductsController@remove')->name('products.remove');
Route::get('/dashboard/pharma/category/{category}','Pharma\ProductsController@manageCategory')->name('products.manageCategory');
Route::get('/dashboard/pharma/subcategory/{subcategory}','Pharma\ProductsController@manageSubcategory')->name('products.manageSubcategory');

Route::resource('dashboard/pharma/products','Pharma\ProductsController');
Route::resource('dashboard/pharma/coupons','Pharma\CouponsController');
Route::resource('dashboard/pharma/categories','Pharma\CategoriesController');
Route::resource('dashboard/pharma/subcategories','Pharma\SubcategoriesController');
Route::get('/dashboard/pharma',function(){
    return view('pharma.dashboard.index');
})->name('pharma.dashboard');



Route::get('dashboard/pharma/manufacturerRequest','Pharma\ManufacturersController@index')->name('manufacturer.requests');

app/Http/Controllers/Doctor/FeedbacksController.php
<?php

namespace App\Http\Controllers\Doctor;

use App\Feedback;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;

class FeedbacksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $feedbacks = Feedback::all()->where('doctor_id',auth()->user()->doctor->id);
        $i=1;
        $section = 'feedback';
        // foreach($feedbacks as $feedback){
        //     $feedbacks[] = User::where('id',$feedback->user_id)->first();
        // }

        // dd($feedbacks);

        return view('doctor.feedback.index',compact([
            'feedbacks',
            'section',
            'i'
        ]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/SlotController.php
<?php

namespace App\Http\Controllers;

use App\Doctor;
use App\Http\Requests\Doctor\Slot\CreateSlotRequest;
use App\Slot;
use App\Type;
use App\SlotDate;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
class SlotController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $doctor = Doctor::find(51);
        $slots_date = $doctor->slot_date;
        $slotsArr = [];

        foreach($slots_date as $slot_date){
            $slotArr = [];
            $slotArr[] = $slot_date;
            $slotArr[] = $slot_date->slots->count();
            $slotArr[] = $slot_date->slots()->where('booked','1')->count();
            $slotsArr[] = $slotArr;
        }
        // dd(date("F j Y, g:i a",strtotime($slots[0]->start_time)));
        return view('doctor.slots.index',compact(['slotsArr']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $doctor = Doctor::find(51);
        $slots_date = $doctor->slot_date;
        return view('doctor.slots.create',compact(['slots_date']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateSlotRequest $request)
    {
        // dd($request);
        $doctor = Doctor::findOrFail(51);
        if($doctor){
            $slot_date = $doctor->slot_date()->create([
                'date'=>$request->slot_date
            ]);
            foreach($request->time as $time){
                $oldTime = $time;
                $slot = $slot_date->slots()->create([
                    'start_time'=>$time
                ]);
                foreach($request->type as $typeName){
                    // dd($time);
                    if(Str::contains($typeName, $oldTime)){
                        // dd(Type::where('name',explode('-',$typeName)[0])->first());
                        $type = Type::where('name',explode('-',$typeName)[0])->first();
                        $type->slots()->attach($slot->id);
                    }
                }
            }


            return redirect(route('slots.index'));
        }
    }


    /**
     * Display the specified resource.
     *
     * @param  \App\Slot  $slot
     * @return \Illuminate\Http\Response
     */
    public function show(Slot $slot)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Slot  $slot
     * @return \Illuminate\Http\Response
     */
    public function edit($slot_date)
    {
        $slot_date = SlotDate::find($slot_date);
        $slots = $slot_date->slots;
        $typeArr = [];
        $section = 'slots';
        foreach($slot_date->slots as $slot){

            $types = $slot->types;
            $typeArr[$slot->id.'clinic'] = '';
            $typeArr[$slot->id.'video'] = '';
            foreach($types as $type){
                if($type->name=='clinic')
                    $typeArr[$slot->id.'clinic'] = 'checked';
                else if($type->name=='video')
                    $typeArr[$slot->id.'video'] = 'checked';
            }

        }
        $typeArr = json_encode($typeArr);
        return view('doctor.slots.edit',compact(['slot_date','slots','typeArr','section']));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Slot  $slot
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $slot_date)
    {
        $slot_date = SlotDate::find($slot_date);
        foreach($request->old as $old){
            if(explode('-',$old)[1]>0)
            {
                $slot = Slot::find(explode('-',$old)[1]);
                foreach($slot->types as $type){
                    $type->slots()->detach($slot->id);
                }
                $slot->update([
                    'start_time'=>explode('-',$old)[0]
                ]);
                foreach($request->type as $typeName){
                    // dd($time);
                    if(Str::contains($typeName, $slot->start_time)){
                        // dd(Type::where('name',explode('-',$typeName)[0])->first());
                        $type = Type::where('name',explode('-',$typeName)[0])->first();
                        $type->slots()->attach($slot->id);
                    }
                }
            }else{
                $oldTime = explode('-',$old)[0];
                $slot = $slot_date->slots()->create([
                    'start_time'=>$oldTime
                ]);
                foreach($request->type as $typeName){
                    // dd($time);
                    if(Str::contains($typeName, $oldTime)){
                        // dd(Type::where('name',explode('-',$typeName)[0])->first());
                        $type = Type::where('name',explode('-',$typeName)[0])->first();
                        $type->slots()->attach($slot->id);
                    }
                }
            }
        }
        return redirect(route('slots.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Slot  $slot
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $slot = Slot::find($request->slot_id);
        foreach($slot->types as $type){
            $type->slots()->detach($slot->id);
        }
        $slot->delete();
        return json_encode(['id'=>$request->id,'delete'=>1]);
    }
}

resources/views/doctor/slots/create.blade.php
@extends('doctor.dashboard.layout')
@section('main-content')
    <div class="create_slote">
        <h3>Create Slots</h3>
        <div class="">
            <div class="row">
                <div class="col-md-6">
                    <form action="{{route('slots.store')}}" method="POST">
                        @csrf
                        <div class="form-group" style="margin-bottom: 15px">
                            <label for="slot_date">Choose Slot Date</label>
                            <input required style="width:200px" type="date"
                                class="form-control"
                                name="slot_date" id="slot_date" placeholder="Choose">
                            @error('slot_date')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror

                        </div>

                        <div class="time-slots-wrapper">
                            <div class="form-group" id="time-slot-1">
                                <div style="display: flex">
                                    <div style="margin-right:10px">
                                        <label for="time-1" style="margin-right: 10px">Pick a time slot</label>
                                        <input type="text" name="time[]" id="time-1" class="timepicker"/>
                                    </div>
                                    <div style="margin-right:10px">
                                        <div>
                                            <label for="clinic" style="margin-right: 3px">Clinic</label>
                                            <input type="checkbox" style="margin-right: 10px"  class="cb" name="type[]" id="clinic-1" data-id="1" value="clinic">
                                            <label for="video" style="margin-right: 3px">Video Call</label>
                                            <input type="checkbox"  class="cb" name="type[]" id="video-1" data-id="1" value="video">
                                            @error('type')
                                                <div class="text-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div style="margin-right:10px">
                                        <a href="" id="delete-slot-1" class="delete-slot"><button class='btn btn-danger btn-sm' style="margin-right: 3px"><i class='fa fa-trash'></i></button></a>
                                    </div>
                                </div>

                            </div>

                        </div>
                        <div style="display: flex;flex-direction: row-reverse;margin-right:25px;"><a href="" class="add-slot"><i class="fa fa-plus"></i> Add Slot</a></div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection
@section('page-level-styles')
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="{{ asset('assets/css/doctor/plugin/wickedpicker/wickedpicker.css') }}" rel="stylesheet">
    <style>
        .fa-chevron-up,.fa-chevron-down{
            display: block;
        }
    </style>
@endsection
@section('page-level-scripts')
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{{ asset('assets/doctors/js/plugin/wickedpicker/wickedpicker.js')}}" type="text/javascript"></script>

    <script>
        var slots_date = {!!$slots_date!!}
        var booked_date = [];
        for(let i=0;i<slots_date.length;i++){
            booked_date[i] = slots_date[i].date;
        }
        console.log(booked_date);
        flatpickr("#slot_date", {
            enableTime: false,
            minDate: "today",
            disable: booked_date,
            dateFormat: "Y-m-d",
        });
        var count = 2;
        var options = {
            twentyFour: true,  //Display 24 hour format, defaults to false
            upArrow: 'fa fa-chevron-up',  //The up arrow class selector to use, for custom CSS
            downArrow: 'fa fa-chevron-down', //The down arrow class selector to use, for custom CSS
            close: 'wickedpicker__close', //The close class selector to use, for custom CSS
            hoverState: 'hover-state', //The hover state class to use, for custom CSS
            title: 'Timepicker', //The Wickedpicker's title,
            showSeconds: true, //Whether or not to show seconds,
            timeSeparator: ':', // The string to put in between hours and minutes (and seconds)
            secondsInterval: 1, //Change interval for seconds, defaults to 1,
            minutesInterval: 1, //Change interval for minutes, defaults to 1
            beforeShow: null, //A function to be called before the Wickedpicker is shown
            afterShow: null, //A function to be called after the Wickedpicker is closed/hidden
            show: null, //A function to be called when the Wickedpicker is shown
            clearable: false, //Make the picker's input clearable (has clickable "x")
        };
        $('#time-1').wickedpicker(options);
        $('.add-slot').click(function(e){
            e.preventDefault();
            $('.time-slots-wrapper').append(`

                <div class="form-group" id="time-slot-${count}">
                    <div style="display: flex">
                        <div style="margin-right:10px">
                            <label for="time-${count}" style="margin-right: 10px">Pick a time slot</label>
                            <input type="text" name="time[]" id="time-${count}" class="timepicker"/>
                        </div>
                        <div style="margin-right:10px">
                            <div>
                                <label for="clinic" style="margin-right: 3px">Clinic</label>
                                <input type="checkbox" style="margin-right: 10px"  class="cb" name="type[]" id="clinic-${count}" data-id="1" value="clinic">
                                <label for="video" style="margin-right: 3px">Video Call</label>
                                <input type="checkbox"  class="cb" name="type[]" id="video-${count}" data-id="1" value="video">
                                @error('type')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div style="margin-right:10px">
                            <a href="" id="delete-slot-${count}" class="delete-slot"><button class='btn btn-danger btn-sm' style="margin-right: 3px"><i class='fa fa-trash'></i></button></a>
                        </div>
                    </div>

                </div>
            `);
            $('#time-'+count).wickedpicker(options);
            count++;
        });
        $('.time-slots-wrapper').on('change','.timepicker',function(e){

            var id = $(this).attr('id').split('-')[1];
            $('#clinic-'+id).val('clinic-'+($(this).val()));
            $('#video-'+id).val('video-'+($(this).val()));

        });
        $('.time-slots-wrapper').on('click','.delete-slot',function(e){
            e.preventDefault();
            var id = $(this).attr('id').split('-')[2];
            $('#time-slot-'+id).remove();
        });
    </script>
@endsection

resources/views/doctor/slots/index.blade.php
@extends('doctor.dashboard.layout')
@section('title','Practo | Doctor Dashboard')
@section('dashboard-title','Your Slots')
@section('main-content')
    <div>
        <div class="" style="display: flex; flex-direction: row-reverse;">
            <a href="{{route('slots.create')}}" class="btn-sm btn-success">Create New</a>
        </div>
        <!--begin: Datatable -->
        <div class="adv-table" style="margin-top: 10px">
            <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="hidden-table-info">
              <thead>
                <tr>
                    <th>Sr.No</th>
                    <th>Date</th>
                    <th>Total Slot</th>
                    <th>Booked Slot</th>
                    <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                @foreach ($slotsArr as $slotArr)
                <tr>
                    <td></td>
                    <td>{{date("F j Y",strtotime($slotArr[0]->date))}}</td>
                    <td>{{$slotArr[1]}}</td>
                    <td>{{$slotArr[2]}}</td>
                    <td class="d-flex">
                        <a class='btn btn-primary btn-sm' style="margin-right: 3px" href="{{route('slot.edit',$slotArr[0]->id)}}"><i class='fa fa-pencil'></i></a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
      </div>

        <!--end: Datatable -->

    </div>
@endsection
@section('page-level-styles')
    <style>
        .d-flex{
            display: flex;
        }
    </style>
@endsection
@section('page-level-scripts')
    <script src="{{ asset('assets/doctors/js/plugin/datatables/datatables.bundle.js')}}" type="text/javascript"></script>
    <script>
        var oTable = $('#hidden-table-info').dataTable({
            "aoColumnDefs": [{
            "bSortable": false,
            "aTargets": [0]
            }],
            "aaSorting": [
            [1, 'asc']
            ]
        });
    </script>
@endsection